segmentation: ../src/main.cpp ../src/segmentation.cpp
	g++ ../src/main.cpp \
	    ../src/segmentation.cpp \
	    -I /Users/kakukogou/MyLib/opencv/modules/core/include \
	    -I /Users/kakukogou/MyLib/opencv/modules/imgproc/include \
	    -I /Users/kakukogou/MyLib/opencv/modules/imgcodecs/include \
	    -I /Users/kakukogou/MyLib/opencv/modules/videoio/include \
	    -I /Users/kakukogou/MyLib/opencv/modules/highgui/include \
	    /Users/kakukogou/MyLib/opencv/release_native_run/lib/libopencv_core.dylib \
	    /Users/kakukogou/MyLib/opencv/release_native_run/lib/libopencv_imgcodecs.dylib \
	    /Users/kakukogou/MyLib/opencv/release_native_run/lib/libopencv_imgproc.dylib \
	    /Users/kakukogou/MyLib/opencv/release_native_run/lib/libopencv_highgui.dylib \
	    -O3